name: food_fo
description: "Food inFormation, clasify and help your needed."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter: ^0.12.1
  image: ^4.5.4

  provider: ^6.1.5+1

  image_picker: ^1.2.0
  camera: ^0.11.3
  image_cropper: ^11.0.0

  http: ^1.5.0

  logger: ^2.6.2

  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/models/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/icon-512.png
  color_dark: "#121212"
  image_dark: assets/icons/icon-512.png

  android_12:
    image: assets/icons/icon-512.png
    icon_background_color: "#ffffff"
    image_dark: assets/icons/icon-512.png
    icon_background_color_dark: "#121212"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21